- alias: hasura
  config:
    configmap: controller-conf
    namespace: freelancer94-hasura
  data: null
  kubeContext: freelancer94
  name: freelancer94
- alias: hasura1
  config:
    configmap: controller-conf
    namespace: freelancer94-hasura
  data: null
  kubeContext: freelancer94
  name: freelancer94
